name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      # - name: Metrics classic
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.classic.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     user: maxim-klenov
      #     template: classic
      #     base: header
      #     base_hireable: yes
      #     config_timezone: Europe/Moscow
      # - name: Most used
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.plugin.languages.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     base: ""
      #     plugin_languages: yes
      #     plugin_languages_ignored: >-
      #       tex, dockerfile, makefile, qmake, lex, cmake, shell,
      #       gnuplot
      #     plugin_languages_limit: 4
      - name: Mildly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: metadata
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: Europe/Moscow
